#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update_Grade
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EnrollmentDatabase")]
	public partial class EnrollmentDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblEmployee(tblEmployee instance);
    partial void UpdatetblEmployee(tblEmployee instance);
    partial void DeletetblEmployee(tblEmployee instance);
    partial void InserttblGradeLevel(tblGradeLevel instance);
    partial void UpdatetblGradeLevel(tblGradeLevel instance);
    partial void DeletetblGradeLevel(tblGradeLevel instance);
    partial void InserttblRecord(tblRecord instance);
    partial void UpdatetblRecord(tblRecord instance);
    partial void DeletetblRecord(tblRecord instance);
    partial void InserttblSchedule(tblSchedule instance);
    partial void UpdatetblSchedule(tblSchedule instance);
    partial void DeletetblSchedule(tblSchedule instance);
    partial void InserttblSection(tblSection instance);
    partial void UpdatetblSection(tblSection instance);
    partial void DeletetblSection(tblSection instance);
    partial void InserttblStudent(tblStudent instance);
    partial void UpdatetblStudent(tblStudent instance);
    partial void DeletetblStudent(tblStudent instance);
    partial void InserttblStudentSection(tblStudentSection instance);
    partial void UpdatetblStudentSection(tblStudentSection instance);
    partial void DeletetblStudentSection(tblStudentSection instance);
    partial void InserttblSubject(tblSubject instance);
    partial void UpdatetblSubject(tblSubject instance);
    partial void DeletetblSubject(tblSubject instance);
    #endregion
		
		public EnrollmentDataDataContext() : 
				base(global::Update_Grade.Properties.Settings.Default.EnrollmentDatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EnrollmentDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EnrollmentDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EnrollmentDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EnrollmentDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblEmployee> tblEmployees
		{
			get
			{
				return this.GetTable<tblEmployee>();
			}
		}
		
		public System.Data.Linq.Table<tblGradeLevel> tblGradeLevels
		{
			get
			{
				return this.GetTable<tblGradeLevel>();
			}
		}
		
		public System.Data.Linq.Table<tblRecord> tblRecords
		{
			get
			{
				return this.GetTable<tblRecord>();
			}
		}
		
		public System.Data.Linq.Table<tblSchedule> tblSchedules
		{
			get
			{
				return this.GetTable<tblSchedule>();
			}
		}
		
		public System.Data.Linq.Table<tblSection> tblSections
		{
			get
			{
				return this.GetTable<tblSection>();
			}
		}
		
		public System.Data.Linq.Table<tblStudent> tblStudents
		{
			get
			{
				return this.GetTable<tblStudent>();
			}
		}
		
		public System.Data.Linq.Table<tblStudentSection> tblStudentSections
		{
			get
			{
				return this.GetTable<tblStudentSection>();
			}
		}
		
		public System.Data.Linq.Table<tblSubject> tblSubjects
		{
			get
			{
				return this.GetTable<tblSubject>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEmployee")]
	public partial class tblEmployee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _employeeID;
		
		private string _employeeName;
		
		private string _classification;
		
		private string _employeeEmail;
		
		private string _employeePass;
		
		private EntitySet<tblRecord> _tblRecords;
		
		private EntitySet<tblSchedule> _tblSchedules;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnemployeeIDChanging(int value);
    partial void OnemployeeIDChanged();
    partial void OnemployeeNameChanging(string value);
    partial void OnemployeeNameChanged();
    partial void OnclassificationChanging(string value);
    partial void OnclassificationChanged();
    partial void OnemployeeEmailChanging(string value);
    partial void OnemployeeEmailChanged();
    partial void OnemployeePassChanging(string value);
    partial void OnemployeePassChanged();
    #endregion
		
		public tblEmployee()
		{
			this._tblRecords = new EntitySet<tblRecord>(new Action<tblRecord>(this.attach_tblRecords), new Action<tblRecord>(this.detach_tblRecords));
			this._tblSchedules = new EntitySet<tblSchedule>(new Action<tblSchedule>(this.attach_tblSchedules), new Action<tblSchedule>(this.detach_tblSchedules));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int employeeID
		{
			get
			{
				return this._employeeID;
			}
			set
			{
				if ((this._employeeID != value))
				{
					this.OnemployeeIDChanging(value);
					this.SendPropertyChanging();
					this._employeeID = value;
					this.SendPropertyChanged("employeeID");
					this.OnemployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string employeeName
		{
			get
			{
				return this._employeeName;
			}
			set
			{
				if ((this._employeeName != value))
				{
					this.OnemployeeNameChanging(value);
					this.SendPropertyChanging();
					this._employeeName = value;
					this.SendPropertyChanged("employeeName");
					this.OnemployeeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classification", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string classification
		{
			get
			{
				return this._classification;
			}
			set
			{
				if ((this._classification != value))
				{
					this.OnclassificationChanging(value);
					this.SendPropertyChanging();
					this._classification = value;
					this.SendPropertyChanged("classification");
					this.OnclassificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeeEmail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string employeeEmail
		{
			get
			{
				return this._employeeEmail;
			}
			set
			{
				if ((this._employeeEmail != value))
				{
					this.OnemployeeEmailChanging(value);
					this.SendPropertyChanging();
					this._employeeEmail = value;
					this.SendPropertyChanged("employeeEmail");
					this.OnemployeeEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeePass", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string employeePass
		{
			get
			{
				return this._employeePass;
			}
			set
			{
				if ((this._employeePass != value))
				{
					this.OnemployeePassChanging(value);
					this.SendPropertyChanging();
					this._employeePass = value;
					this.SendPropertyChanged("employeePass");
					this.OnemployeePassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEmployee_tblRecord", Storage="_tblRecords", ThisKey="employeeID", OtherKey="employeeID")]
		public EntitySet<tblRecord> tblRecords
		{
			get
			{
				return this._tblRecords;
			}
			set
			{
				this._tblRecords.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEmployee_tblSchedule", Storage="_tblSchedules", ThisKey="employeeID", OtherKey="employeeID")]
		public EntitySet<tblSchedule> tblSchedules
		{
			get
			{
				return this._tblSchedules;
			}
			set
			{
				this._tblSchedules.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblRecords(tblRecord entity)
		{
			this.SendPropertyChanging();
			entity.tblEmployee = this;
		}
		
		private void detach_tblRecords(tblRecord entity)
		{
			this.SendPropertyChanging();
			entity.tblEmployee = null;
		}
		
		private void attach_tblSchedules(tblSchedule entity)
		{
			this.SendPropertyChanging();
			entity.tblEmployee = this;
		}
		
		private void detach_tblSchedules(tblSchedule entity)
		{
			this.SendPropertyChanging();
			entity.tblEmployee = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblGradeLevel")]
	public partial class tblGradeLevel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _gradeLevelID;
		
		private int _gradeLevel;
		
		private string _strand;
		
		private EntitySet<tblSchedule> _tblSchedules;
		
		private EntitySet<tblStudent> _tblStudents;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngradeLevelIDChanging(int value);
    partial void OngradeLevelIDChanged();
    partial void OngradeLevelChanging(int value);
    partial void OngradeLevelChanged();
    partial void OnstrandChanging(string value);
    partial void OnstrandChanged();
    #endregion
		
		public tblGradeLevel()
		{
			this._tblSchedules = new EntitySet<tblSchedule>(new Action<tblSchedule>(this.attach_tblSchedules), new Action<tblSchedule>(this.detach_tblSchedules));
			this._tblStudents = new EntitySet<tblStudent>(new Action<tblStudent>(this.attach_tblStudents), new Action<tblStudent>(this.detach_tblStudents));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gradeLevelID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int gradeLevelID
		{
			get
			{
				return this._gradeLevelID;
			}
			set
			{
				if ((this._gradeLevelID != value))
				{
					this.OngradeLevelIDChanging(value);
					this.SendPropertyChanging();
					this._gradeLevelID = value;
					this.SendPropertyChanged("gradeLevelID");
					this.OngradeLevelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gradeLevel", DbType="Int NOT NULL")]
		public int gradeLevel
		{
			get
			{
				return this._gradeLevel;
			}
			set
			{
				if ((this._gradeLevel != value))
				{
					this.OngradeLevelChanging(value);
					this.SendPropertyChanging();
					this._gradeLevel = value;
					this.SendPropertyChanged("gradeLevel");
					this.OngradeLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strand", DbType="NVarChar(50)")]
		public string strand
		{
			get
			{
				return this._strand;
			}
			set
			{
				if ((this._strand != value))
				{
					this.OnstrandChanging(value);
					this.SendPropertyChanging();
					this._strand = value;
					this.SendPropertyChanged("strand");
					this.OnstrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblGradeLevel_tblSchedule", Storage="_tblSchedules", ThisKey="gradeLevelID", OtherKey="gradeLevelID")]
		public EntitySet<tblSchedule> tblSchedules
		{
			get
			{
				return this._tblSchedules;
			}
			set
			{
				this._tblSchedules.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblGradeLevel_tblStudent", Storage="_tblStudents", ThisKey="gradeLevelID", OtherKey="gradeLevelID")]
		public EntitySet<tblStudent> tblStudents
		{
			get
			{
				return this._tblStudents;
			}
			set
			{
				this._tblStudents.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSchedules(tblSchedule entity)
		{
			this.SendPropertyChanging();
			entity.tblGradeLevel = this;
		}
		
		private void detach_tblSchedules(tblSchedule entity)
		{
			this.SendPropertyChanging();
			entity.tblGradeLevel = null;
		}
		
		private void attach_tblStudents(tblStudent entity)
		{
			this.SendPropertyChanging();
			entity.tblGradeLevel = this;
		}
		
		private void detach_tblStudents(tblStudent entity)
		{
			this.SendPropertyChanging();
			entity.tblGradeLevel = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblRecord")]
	public partial class tblRecord : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _recordID;
		
		private int _studentID;
		
		private string _schoolName;
		
		private string _schoolYear;
		
		private int _schoolTerm;
		
		private int _subjectID;
		
		private int _grade;
		
		private string _gradeStatus;
		
		private int _employeeID;
		
		private EntityRef<tblEmployee> _tblEmployee;
		
		private EntityRef<tblStudent> _tblStudent;
		
		private EntityRef<tblSubject> _tblSubject;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnrecordIDChanging(int value);
    partial void OnrecordIDChanged();
    partial void OnstudentIDChanging(int value);
    partial void OnstudentIDChanged();
    partial void OnschoolNameChanging(string value);
    partial void OnschoolNameChanged();
    partial void OnschoolYearChanging(string value);
    partial void OnschoolYearChanged();
    partial void OnschoolTermChanging(int value);
    partial void OnschoolTermChanged();
    partial void OnsubjectIDChanging(int value);
    partial void OnsubjectIDChanged();
    partial void OngradeChanging(int value);
    partial void OngradeChanged();
    partial void OngradeStatusChanging(string value);
    partial void OngradeStatusChanged();
    partial void OnemployeeIDChanging(int value);
    partial void OnemployeeIDChanged();
    #endregion
		
		public tblRecord()
		{
			this._tblEmployee = default(EntityRef<tblEmployee>);
			this._tblStudent = default(EntityRef<tblStudent>);
			this._tblSubject = default(EntityRef<tblSubject>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recordID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int recordID
		{
			get
			{
				return this._recordID;
			}
			set
			{
				if ((this._recordID != value))
				{
					this.OnrecordIDChanging(value);
					this.SendPropertyChanging();
					this._recordID = value;
					this.SendPropertyChanged("recordID");
					this.OnrecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentID", DbType="Int NOT NULL")]
		public int studentID
		{
			get
			{
				return this._studentID;
			}
			set
			{
				if ((this._studentID != value))
				{
					if (this._tblStudent.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstudentIDChanging(value);
					this.SendPropertyChanging();
					this._studentID = value;
					this.SendPropertyChanged("studentID");
					this.OnstudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schoolName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string schoolName
		{
			get
			{
				return this._schoolName;
			}
			set
			{
				if ((this._schoolName != value))
				{
					this.OnschoolNameChanging(value);
					this.SendPropertyChanging();
					this._schoolName = value;
					this.SendPropertyChanged("schoolName");
					this.OnschoolNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schoolYear", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string schoolYear
		{
			get
			{
				return this._schoolYear;
			}
			set
			{
				if ((this._schoolYear != value))
				{
					this.OnschoolYearChanging(value);
					this.SendPropertyChanging();
					this._schoolYear = value;
					this.SendPropertyChanged("schoolYear");
					this.OnschoolYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schoolTerm", DbType="Int NOT NULL")]
		public int schoolTerm
		{
			get
			{
				return this._schoolTerm;
			}
			set
			{
				if ((this._schoolTerm != value))
				{
					this.OnschoolTermChanging(value);
					this.SendPropertyChanging();
					this._schoolTerm = value;
					this.SendPropertyChanged("schoolTerm");
					this.OnschoolTermChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subjectID", DbType="Int NOT NULL")]
		public int subjectID
		{
			get
			{
				return this._subjectID;
			}
			set
			{
				if ((this._subjectID != value))
				{
					if (this._tblSubject.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsubjectIDChanging(value);
					this.SendPropertyChanging();
					this._subjectID = value;
					this.SendPropertyChanged("subjectID");
					this.OnsubjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade", DbType="Int NOT NULL")]
		public int grade
		{
			get
			{
				return this._grade;
			}
			set
			{
				if ((this._grade != value))
				{
					this.OngradeChanging(value);
					this.SendPropertyChanging();
					this._grade = value;
					this.SendPropertyChanged("grade");
					this.OngradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gradeStatus", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string gradeStatus
		{
			get
			{
				return this._gradeStatus;
			}
			set
			{
				if ((this._gradeStatus != value))
				{
					this.OngradeStatusChanging(value);
					this.SendPropertyChanging();
					this._gradeStatus = value;
					this.SendPropertyChanged("gradeStatus");
					this.OngradeStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeeID", DbType="Int NOT NULL")]
		public int employeeID
		{
			get
			{
				return this._employeeID;
			}
			set
			{
				if ((this._employeeID != value))
				{
					if (this._tblEmployee.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnemployeeIDChanging(value);
					this.SendPropertyChanging();
					this._employeeID = value;
					this.SendPropertyChanged("employeeID");
					this.OnemployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEmployee_tblRecord", Storage="_tblEmployee", ThisKey="employeeID", OtherKey="employeeID", IsForeignKey=true)]
		public tblEmployee tblEmployee
		{
			get
			{
				return this._tblEmployee.Entity;
			}
			set
			{
				tblEmployee previousValue = this._tblEmployee.Entity;
				if (((previousValue != value) 
							|| (this._tblEmployee.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblEmployee.Entity = null;
						previousValue.tblRecords.Remove(this);
					}
					this._tblEmployee.Entity = value;
					if ((value != null))
					{
						value.tblRecords.Add(this);
						this._employeeID = value.employeeID;
					}
					else
					{
						this._employeeID = default(int);
					}
					this.SendPropertyChanged("tblEmployee");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblStudent_tblRecord", Storage="_tblStudent", ThisKey="studentID", OtherKey="StudentID", IsForeignKey=true)]
		public tblStudent tblStudent
		{
			get
			{
				return this._tblStudent.Entity;
			}
			set
			{
				tblStudent previousValue = this._tblStudent.Entity;
				if (((previousValue != value) 
							|| (this._tblStudent.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblStudent.Entity = null;
						previousValue.tblRecords.Remove(this);
					}
					this._tblStudent.Entity = value;
					if ((value != null))
					{
						value.tblRecords.Add(this);
						this._studentID = value.StudentID;
					}
					else
					{
						this._studentID = default(int);
					}
					this.SendPropertyChanged("tblStudent");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSubject_tblRecord", Storage="_tblSubject", ThisKey="subjectID", OtherKey="subjectID", IsForeignKey=true)]
		public tblSubject tblSubject
		{
			get
			{
				return this._tblSubject.Entity;
			}
			set
			{
				tblSubject previousValue = this._tblSubject.Entity;
				if (((previousValue != value) 
							|| (this._tblSubject.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSubject.Entity = null;
						previousValue.tblRecords.Remove(this);
					}
					this._tblSubject.Entity = value;
					if ((value != null))
					{
						value.tblRecords.Add(this);
						this._subjectID = value.subjectID;
					}
					else
					{
						this._subjectID = default(int);
					}
					this.SendPropertyChanged("tblSubject");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSchedule")]
	public partial class tblSchedule : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _scheduleID;
		
		private string _classPeriod;
		
		private string _classDay;
		
		private int _subjectID;
		
		private int _employeeID;
		
		private int _gradeLevelID;
		
		private int _sectionID;
		
		private EntityRef<tblEmployee> _tblEmployee;
		
		private EntityRef<tblGradeLevel> _tblGradeLevel;
		
		private EntityRef<tblSection> _tblSection;
		
		private EntityRef<tblSubject> _tblSubject;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnscheduleIDChanging(int value);
    partial void OnscheduleIDChanged();
    partial void OnclassPeriodChanging(string value);
    partial void OnclassPeriodChanged();
    partial void OnclassDayChanging(string value);
    partial void OnclassDayChanged();
    partial void OnsubjectIDChanging(int value);
    partial void OnsubjectIDChanged();
    partial void OnemployeeIDChanging(int value);
    partial void OnemployeeIDChanged();
    partial void OngradeLevelIDChanging(int value);
    partial void OngradeLevelIDChanged();
    partial void OnsectionIDChanging(int value);
    partial void OnsectionIDChanged();
    #endregion
		
		public tblSchedule()
		{
			this._tblEmployee = default(EntityRef<tblEmployee>);
			this._tblGradeLevel = default(EntityRef<tblGradeLevel>);
			this._tblSection = default(EntityRef<tblSection>);
			this._tblSubject = default(EntityRef<tblSubject>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scheduleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int scheduleID
		{
			get
			{
				return this._scheduleID;
			}
			set
			{
				if ((this._scheduleID != value))
				{
					this.OnscheduleIDChanging(value);
					this.SendPropertyChanging();
					this._scheduleID = value;
					this.SendPropertyChanged("scheduleID");
					this.OnscheduleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classPeriod", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string classPeriod
		{
			get
			{
				return this._classPeriod;
			}
			set
			{
				if ((this._classPeriod != value))
				{
					this.OnclassPeriodChanging(value);
					this.SendPropertyChanging();
					this._classPeriod = value;
					this.SendPropertyChanged("classPeriod");
					this.OnclassPeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classDay", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string classDay
		{
			get
			{
				return this._classDay;
			}
			set
			{
				if ((this._classDay != value))
				{
					this.OnclassDayChanging(value);
					this.SendPropertyChanging();
					this._classDay = value;
					this.SendPropertyChanged("classDay");
					this.OnclassDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subjectID", DbType="Int NOT NULL")]
		public int subjectID
		{
			get
			{
				return this._subjectID;
			}
			set
			{
				if ((this._subjectID != value))
				{
					if (this._tblSubject.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsubjectIDChanging(value);
					this.SendPropertyChanging();
					this._subjectID = value;
					this.SendPropertyChanged("subjectID");
					this.OnsubjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeeID", DbType="Int NOT NULL")]
		public int employeeID
		{
			get
			{
				return this._employeeID;
			}
			set
			{
				if ((this._employeeID != value))
				{
					if (this._tblEmployee.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnemployeeIDChanging(value);
					this.SendPropertyChanging();
					this._employeeID = value;
					this.SendPropertyChanged("employeeID");
					this.OnemployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gradeLevelID", DbType="Int NOT NULL")]
		public int gradeLevelID
		{
			get
			{
				return this._gradeLevelID;
			}
			set
			{
				if ((this._gradeLevelID != value))
				{
					if (this._tblGradeLevel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OngradeLevelIDChanging(value);
					this.SendPropertyChanging();
					this._gradeLevelID = value;
					this.SendPropertyChanged("gradeLevelID");
					this.OngradeLevelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionID", DbType="Int NOT NULL")]
		public int sectionID
		{
			get
			{
				return this._sectionID;
			}
			set
			{
				if ((this._sectionID != value))
				{
					if (this._tblSection.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsectionIDChanging(value);
					this.SendPropertyChanging();
					this._sectionID = value;
					this.SendPropertyChanged("sectionID");
					this.OnsectionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEmployee_tblSchedule", Storage="_tblEmployee", ThisKey="employeeID", OtherKey="employeeID", IsForeignKey=true)]
		public tblEmployee tblEmployee
		{
			get
			{
				return this._tblEmployee.Entity;
			}
			set
			{
				tblEmployee previousValue = this._tblEmployee.Entity;
				if (((previousValue != value) 
							|| (this._tblEmployee.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblEmployee.Entity = null;
						previousValue.tblSchedules.Remove(this);
					}
					this._tblEmployee.Entity = value;
					if ((value != null))
					{
						value.tblSchedules.Add(this);
						this._employeeID = value.employeeID;
					}
					else
					{
						this._employeeID = default(int);
					}
					this.SendPropertyChanged("tblEmployee");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblGradeLevel_tblSchedule", Storage="_tblGradeLevel", ThisKey="gradeLevelID", OtherKey="gradeLevelID", IsForeignKey=true)]
		public tblGradeLevel tblGradeLevel
		{
			get
			{
				return this._tblGradeLevel.Entity;
			}
			set
			{
				tblGradeLevel previousValue = this._tblGradeLevel.Entity;
				if (((previousValue != value) 
							|| (this._tblGradeLevel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblGradeLevel.Entity = null;
						previousValue.tblSchedules.Remove(this);
					}
					this._tblGradeLevel.Entity = value;
					if ((value != null))
					{
						value.tblSchedules.Add(this);
						this._gradeLevelID = value.gradeLevelID;
					}
					else
					{
						this._gradeLevelID = default(int);
					}
					this.SendPropertyChanged("tblGradeLevel");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSection_tblSchedule", Storage="_tblSection", ThisKey="sectionID", OtherKey="sectionID", IsForeignKey=true)]
		public tblSection tblSection
		{
			get
			{
				return this._tblSection.Entity;
			}
			set
			{
				tblSection previousValue = this._tblSection.Entity;
				if (((previousValue != value) 
							|| (this._tblSection.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSection.Entity = null;
						previousValue.tblSchedules.Remove(this);
					}
					this._tblSection.Entity = value;
					if ((value != null))
					{
						value.tblSchedules.Add(this);
						this._sectionID = value.sectionID;
					}
					else
					{
						this._sectionID = default(int);
					}
					this.SendPropertyChanged("tblSection");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSubject_tblSchedule", Storage="_tblSubject", ThisKey="subjectID", OtherKey="subjectID", IsForeignKey=true)]
		public tblSubject tblSubject
		{
			get
			{
				return this._tblSubject.Entity;
			}
			set
			{
				tblSubject previousValue = this._tblSubject.Entity;
				if (((previousValue != value) 
							|| (this._tblSubject.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSubject.Entity = null;
						previousValue.tblSchedules.Remove(this);
					}
					this._tblSubject.Entity = value;
					if ((value != null))
					{
						value.tblSchedules.Add(this);
						this._subjectID = value.subjectID;
					}
					else
					{
						this._subjectID = default(int);
					}
					this.SendPropertyChanged("tblSubject");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSection")]
	public partial class tblSection : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sectionID;
		
		private string _sectionName;
		
		private EntitySet<tblSchedule> _tblSchedules;
		
		private EntitySet<tblStudentSection> _tblStudentSections;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsectionIDChanging(int value);
    partial void OnsectionIDChanged();
    partial void OnsectionNameChanging(string value);
    partial void OnsectionNameChanged();
    #endregion
		
		public tblSection()
		{
			this._tblSchedules = new EntitySet<tblSchedule>(new Action<tblSchedule>(this.attach_tblSchedules), new Action<tblSchedule>(this.detach_tblSchedules));
			this._tblStudentSections = new EntitySet<tblStudentSection>(new Action<tblStudentSection>(this.attach_tblStudentSections), new Action<tblStudentSection>(this.detach_tblStudentSections));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int sectionID
		{
			get
			{
				return this._sectionID;
			}
			set
			{
				if ((this._sectionID != value))
				{
					this.OnsectionIDChanging(value);
					this.SendPropertyChanging();
					this._sectionID = value;
					this.SendPropertyChanged("sectionID");
					this.OnsectionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sectionName
		{
			get
			{
				return this._sectionName;
			}
			set
			{
				if ((this._sectionName != value))
				{
					this.OnsectionNameChanging(value);
					this.SendPropertyChanging();
					this._sectionName = value;
					this.SendPropertyChanged("sectionName");
					this.OnsectionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSection_tblSchedule", Storage="_tblSchedules", ThisKey="sectionID", OtherKey="sectionID")]
		public EntitySet<tblSchedule> tblSchedules
		{
			get
			{
				return this._tblSchedules;
			}
			set
			{
				this._tblSchedules.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSection_tblStudentSection", Storage="_tblStudentSections", ThisKey="sectionID", OtherKey="sectionID")]
		public EntitySet<tblStudentSection> tblStudentSections
		{
			get
			{
				return this._tblStudentSections;
			}
			set
			{
				this._tblStudentSections.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSchedules(tblSchedule entity)
		{
			this.SendPropertyChanging();
			entity.tblSection = this;
		}
		
		private void detach_tblSchedules(tblSchedule entity)
		{
			this.SendPropertyChanging();
			entity.tblSection = null;
		}
		
		private void attach_tblStudentSections(tblStudentSection entity)
		{
			this.SendPropertyChanging();
			entity.tblSection = this;
		}
		
		private void detach_tblStudentSections(tblStudentSection entity)
		{
			this.SendPropertyChanging();
			entity.tblSection = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblStudent")]
	public partial class tblStudent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StudentID;
		
		private string _studentName;
		
		private int _gradeLevelID;
		
		private string _studentContactNumber;
		
		private string _studentEmail;
		
		private string _studentAddress;
		
		private System.DateTime _studentDateOfBirth;
		
		private string _studentImage;
		
		private string _studentGender;
		
		private string _studentNationality;
		
		private string _studentStatus;
		
		private string _paymentPlan;
		
		private EntitySet<tblRecord> _tblRecords;
		
		private EntitySet<tblStudentSection> _tblStudentSections;
		
		private EntityRef<tblGradeLevel> _tblGradeLevel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudentIDChanging(int value);
    partial void OnStudentIDChanged();
    partial void OnstudentNameChanging(string value);
    partial void OnstudentNameChanged();
    partial void OngradeLevelIDChanging(int value);
    partial void OngradeLevelIDChanged();
    partial void OnstudentContactNumberChanging(string value);
    partial void OnstudentContactNumberChanged();
    partial void OnstudentEmailChanging(string value);
    partial void OnstudentEmailChanged();
    partial void OnstudentAddressChanging(string value);
    partial void OnstudentAddressChanged();
    partial void OnstudentDateOfBirthChanging(System.DateTime value);
    partial void OnstudentDateOfBirthChanged();
    partial void OnstudentImageChanging(string value);
    partial void OnstudentImageChanged();
    partial void OnstudentGenderChanging(string value);
    partial void OnstudentGenderChanged();
    partial void OnstudentNationalityChanging(string value);
    partial void OnstudentNationalityChanged();
    partial void OnstudentStatusChanging(string value);
    partial void OnstudentStatusChanged();
    partial void OnpaymentPlanChanging(string value);
    partial void OnpaymentPlanChanged();
    #endregion
		
		public tblStudent()
		{
			this._tblRecords = new EntitySet<tblRecord>(new Action<tblRecord>(this.attach_tblRecords), new Action<tblRecord>(this.detach_tblRecords));
			this._tblStudentSections = new EntitySet<tblStudentSection>(new Action<tblStudentSection>(this.attach_tblStudentSections), new Action<tblStudentSection>(this.detach_tblStudentSections));
			this._tblGradeLevel = default(EntityRef<tblGradeLevel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StudentID
		{
			get
			{
				return this._StudentID;
			}
			set
			{
				if ((this._StudentID != value))
				{
					this.OnStudentIDChanging(value);
					this.SendPropertyChanging();
					this._StudentID = value;
					this.SendPropertyChanged("StudentID");
					this.OnStudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string studentName
		{
			get
			{
				return this._studentName;
			}
			set
			{
				if ((this._studentName != value))
				{
					this.OnstudentNameChanging(value);
					this.SendPropertyChanging();
					this._studentName = value;
					this.SendPropertyChanged("studentName");
					this.OnstudentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gradeLevelID", DbType="Int NOT NULL")]
		public int gradeLevelID
		{
			get
			{
				return this._gradeLevelID;
			}
			set
			{
				if ((this._gradeLevelID != value))
				{
					if (this._tblGradeLevel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OngradeLevelIDChanging(value);
					this.SendPropertyChanging();
					this._gradeLevelID = value;
					this.SendPropertyChanged("gradeLevelID");
					this.OngradeLevelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentContactNumber", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
		public string studentContactNumber
		{
			get
			{
				return this._studentContactNumber;
			}
			set
			{
				if ((this._studentContactNumber != value))
				{
					this.OnstudentContactNumberChanging(value);
					this.SendPropertyChanging();
					this._studentContactNumber = value;
					this.SendPropertyChanged("studentContactNumber");
					this.OnstudentContactNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentEmail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string studentEmail
		{
			get
			{
				return this._studentEmail;
			}
			set
			{
				if ((this._studentEmail != value))
				{
					this.OnstudentEmailChanging(value);
					this.SendPropertyChanging();
					this._studentEmail = value;
					this.SendPropertyChanged("studentEmail");
					this.OnstudentEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentAddress", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string studentAddress
		{
			get
			{
				return this._studentAddress;
			}
			set
			{
				if ((this._studentAddress != value))
				{
					this.OnstudentAddressChanging(value);
					this.SendPropertyChanging();
					this._studentAddress = value;
					this.SendPropertyChanged("studentAddress");
					this.OnstudentAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentDateOfBirth", DbType="Date NOT NULL")]
		public System.DateTime studentDateOfBirth
		{
			get
			{
				return this._studentDateOfBirth;
			}
			set
			{
				if ((this._studentDateOfBirth != value))
				{
					this.OnstudentDateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._studentDateOfBirth = value;
					this.SendPropertyChanged("studentDateOfBirth");
					this.OnstudentDateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentImage", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string studentImage
		{
			get
			{
				return this._studentImage;
			}
			set
			{
				if ((this._studentImage != value))
				{
					this.OnstudentImageChanging(value);
					this.SendPropertyChanging();
					this._studentImage = value;
					this.SendPropertyChanged("studentImage");
					this.OnstudentImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentGender", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string studentGender
		{
			get
			{
				return this._studentGender;
			}
			set
			{
				if ((this._studentGender != value))
				{
					this.OnstudentGenderChanging(value);
					this.SendPropertyChanging();
					this._studentGender = value;
					this.SendPropertyChanged("studentGender");
					this.OnstudentGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentNationality", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string studentNationality
		{
			get
			{
				return this._studentNationality;
			}
			set
			{
				if ((this._studentNationality != value))
				{
					this.OnstudentNationalityChanging(value);
					this.SendPropertyChanging();
					this._studentNationality = value;
					this.SendPropertyChanged("studentNationality");
					this.OnstudentNationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentStatus", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string studentStatus
		{
			get
			{
				return this._studentStatus;
			}
			set
			{
				if ((this._studentStatus != value))
				{
					this.OnstudentStatusChanging(value);
					this.SendPropertyChanging();
					this._studentStatus = value;
					this.SendPropertyChanged("studentStatus");
					this.OnstudentStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymentPlan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string paymentPlan
		{
			get
			{
				return this._paymentPlan;
			}
			set
			{
				if ((this._paymentPlan != value))
				{
					this.OnpaymentPlanChanging(value);
					this.SendPropertyChanging();
					this._paymentPlan = value;
					this.SendPropertyChanged("paymentPlan");
					this.OnpaymentPlanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblStudent_tblRecord", Storage="_tblRecords", ThisKey="StudentID", OtherKey="studentID")]
		public EntitySet<tblRecord> tblRecords
		{
			get
			{
				return this._tblRecords;
			}
			set
			{
				this._tblRecords.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblStudent_tblStudentSection", Storage="_tblStudentSections", ThisKey="StudentID", OtherKey="studentID")]
		public EntitySet<tblStudentSection> tblStudentSections
		{
			get
			{
				return this._tblStudentSections;
			}
			set
			{
				this._tblStudentSections.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblGradeLevel_tblStudent", Storage="_tblGradeLevel", ThisKey="gradeLevelID", OtherKey="gradeLevelID", IsForeignKey=true)]
		public tblGradeLevel tblGradeLevel
		{
			get
			{
				return this._tblGradeLevel.Entity;
			}
			set
			{
				tblGradeLevel previousValue = this._tblGradeLevel.Entity;
				if (((previousValue != value) 
							|| (this._tblGradeLevel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblGradeLevel.Entity = null;
						previousValue.tblStudents.Remove(this);
					}
					this._tblGradeLevel.Entity = value;
					if ((value != null))
					{
						value.tblStudents.Add(this);
						this._gradeLevelID = value.gradeLevelID;
					}
					else
					{
						this._gradeLevelID = default(int);
					}
					this.SendPropertyChanged("tblGradeLevel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblRecords(tblRecord entity)
		{
			this.SendPropertyChanging();
			entity.tblStudent = this;
		}
		
		private void detach_tblRecords(tblRecord entity)
		{
			this.SendPropertyChanging();
			entity.tblStudent = null;
		}
		
		private void attach_tblStudentSections(tblStudentSection entity)
		{
			this.SendPropertyChanging();
			entity.tblStudent = this;
		}
		
		private void detach_tblStudentSections(tblStudentSection entity)
		{
			this.SendPropertyChanging();
			entity.tblStudent = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblStudentSection")]
	public partial class tblStudentSection : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _studentSectionID;
		
		private int _studentID;
		
		private int _sectionID;
		
		private EntityRef<tblSection> _tblSection;
		
		private EntityRef<tblStudent> _tblStudent;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstudentSectionIDChanging(int value);
    partial void OnstudentSectionIDChanged();
    partial void OnstudentIDChanging(int value);
    partial void OnstudentIDChanged();
    partial void OnsectionIDChanging(int value);
    partial void OnsectionIDChanged();
    #endregion
		
		public tblStudentSection()
		{
			this._tblSection = default(EntityRef<tblSection>);
			this._tblStudent = default(EntityRef<tblStudent>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentSectionID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int studentSectionID
		{
			get
			{
				return this._studentSectionID;
			}
			set
			{
				if ((this._studentSectionID != value))
				{
					this.OnstudentSectionIDChanging(value);
					this.SendPropertyChanging();
					this._studentSectionID = value;
					this.SendPropertyChanged("studentSectionID");
					this.OnstudentSectionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentID", DbType="Int NOT NULL")]
		public int studentID
		{
			get
			{
				return this._studentID;
			}
			set
			{
				if ((this._studentID != value))
				{
					if (this._tblStudent.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstudentIDChanging(value);
					this.SendPropertyChanging();
					this._studentID = value;
					this.SendPropertyChanged("studentID");
					this.OnstudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionID", DbType="Int NOT NULL")]
		public int sectionID
		{
			get
			{
				return this._sectionID;
			}
			set
			{
				if ((this._sectionID != value))
				{
					if (this._tblSection.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsectionIDChanging(value);
					this.SendPropertyChanging();
					this._sectionID = value;
					this.SendPropertyChanged("sectionID");
					this.OnsectionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSection_tblStudentSection", Storage="_tblSection", ThisKey="sectionID", OtherKey="sectionID", IsForeignKey=true)]
		public tblSection tblSection
		{
			get
			{
				return this._tblSection.Entity;
			}
			set
			{
				tblSection previousValue = this._tblSection.Entity;
				if (((previousValue != value) 
							|| (this._tblSection.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSection.Entity = null;
						previousValue.tblStudentSections.Remove(this);
					}
					this._tblSection.Entity = value;
					if ((value != null))
					{
						value.tblStudentSections.Add(this);
						this._sectionID = value.sectionID;
					}
					else
					{
						this._sectionID = default(int);
					}
					this.SendPropertyChanged("tblSection");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblStudent_tblStudentSection", Storage="_tblStudent", ThisKey="studentID", OtherKey="StudentID", IsForeignKey=true)]
		public tblStudent tblStudent
		{
			get
			{
				return this._tblStudent.Entity;
			}
			set
			{
				tblStudent previousValue = this._tblStudent.Entity;
				if (((previousValue != value) 
							|| (this._tblStudent.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblStudent.Entity = null;
						previousValue.tblStudentSections.Remove(this);
					}
					this._tblStudent.Entity = value;
					if ((value != null))
					{
						value.tblStudentSections.Add(this);
						this._studentID = value.StudentID;
					}
					else
					{
						this._studentID = default(int);
					}
					this.SendPropertyChanged("tblStudent");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSubject")]
	public partial class tblSubject : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _subjectID;
		
		private string _subjectName;
		
		private EntitySet<tblRecord> _tblRecords;
		
		private EntitySet<tblSchedule> _tblSchedules;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsubjectIDChanging(int value);
    partial void OnsubjectIDChanged();
    partial void OnsubjectNameChanging(string value);
    partial void OnsubjectNameChanged();
    #endregion
		
		public tblSubject()
		{
			this._tblRecords = new EntitySet<tblRecord>(new Action<tblRecord>(this.attach_tblRecords), new Action<tblRecord>(this.detach_tblRecords));
			this._tblSchedules = new EntitySet<tblSchedule>(new Action<tblSchedule>(this.attach_tblSchedules), new Action<tblSchedule>(this.detach_tblSchedules));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subjectID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int subjectID
		{
			get
			{
				return this._subjectID;
			}
			set
			{
				if ((this._subjectID != value))
				{
					this.OnsubjectIDChanging(value);
					this.SendPropertyChanging();
					this._subjectID = value;
					this.SendPropertyChanged("subjectID");
					this.OnsubjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subjectName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string subjectName
		{
			get
			{
				return this._subjectName;
			}
			set
			{
				if ((this._subjectName != value))
				{
					this.OnsubjectNameChanging(value);
					this.SendPropertyChanging();
					this._subjectName = value;
					this.SendPropertyChanged("subjectName");
					this.OnsubjectNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSubject_tblRecord", Storage="_tblRecords", ThisKey="subjectID", OtherKey="subjectID")]
		public EntitySet<tblRecord> tblRecords
		{
			get
			{
				return this._tblRecords;
			}
			set
			{
				this._tblRecords.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSubject_tblSchedule", Storage="_tblSchedules", ThisKey="subjectID", OtherKey="subjectID")]
		public EntitySet<tblSchedule> tblSchedules
		{
			get
			{
				return this._tblSchedules;
			}
			set
			{
				this._tblSchedules.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblRecords(tblRecord entity)
		{
			this.SendPropertyChanging();
			entity.tblSubject = this;
		}
		
		private void detach_tblRecords(tblRecord entity)
		{
			this.SendPropertyChanging();
			entity.tblSubject = null;
		}
		
		private void attach_tblSchedules(tblSchedule entity)
		{
			this.SendPropertyChanging();
			entity.tblSubject = this;
		}
		
		private void detach_tblSchedules(tblSchedule entity)
		{
			this.SendPropertyChanging();
			entity.tblSubject = null;
		}
	}
}
#pragma warning restore 1591
