<?xml version="1.0" encoding="utf-8"?><Database Name="EnrollmentDatabase" Class="EnrollmentDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-LU9MQ50\SQLEXPRESS;Initial Catalog=EnrollmentDatabase;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=True" SettingsObjectName="Update_Grade.Properties.Settings" SettingsPropertyName="EnrollmentDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblEmployee" Member="tblEmployees">
    <Type Name="tblEmployee">
      <Column Name="employeeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="employeeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="classification" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="employeeEmail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="employeePass" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="tblEmployee_tblRecord" Member="tblRecords" ThisKey="employeeID" OtherKey="employeeID" Type="tblRecord" />
      <Association Name="tblEmployee_tblSchedule" Member="tblSchedules" ThisKey="employeeID" OtherKey="employeeID" Type="tblSchedule" />
    </Type>
  </Table>
  <Table Name="dbo.tblGradeLevel" Member="tblGradeLevels">
    <Type Name="tblGradeLevel">
      <Column Name="gradeLevelID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="gradeLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="strand" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tblGradeLevel_tblSchedule" Member="tblSchedules" ThisKey="gradeLevelID" OtherKey="gradeLevelID" Type="tblSchedule" />
      <Association Name="tblGradeLevel_tblStudent" Member="tblStudents" ThisKey="gradeLevelID" OtherKey="gradeLevelID" Type="tblStudent" />
    </Type>
  </Table>
  <Table Name="dbo.tblRecord" Member="tblRecords">
    <Type Name="tblRecord">
      <Column Name="recordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="schoolName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="schoolYear" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="schoolTerm" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="subjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="grade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="gradeStatus" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="employeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblEmployee_tblRecord" Member="tblEmployee" ThisKey="employeeID" OtherKey="employeeID" Type="tblEmployee" IsForeignKey="true" />
      <Association Name="tblStudent_tblRecord" Member="tblStudent" ThisKey="studentID" OtherKey="StudentID" Type="tblStudent" IsForeignKey="true" />
      <Association Name="tblSubject_tblRecord" Member="tblSubject" ThisKey="subjectID" OtherKey="subjectID" Type="tblSubject" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSchedule" Member="tblSchedules">
    <Type Name="tblSchedule">
      <Column Name="scheduleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="classPeriod" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="classDay" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="subjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="employeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="gradeLevelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sectionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblEmployee_tblSchedule" Member="tblEmployee" ThisKey="employeeID" OtherKey="employeeID" Type="tblEmployee" IsForeignKey="true" />
      <Association Name="tblGradeLevel_tblSchedule" Member="tblGradeLevel" ThisKey="gradeLevelID" OtherKey="gradeLevelID" Type="tblGradeLevel" IsForeignKey="true" />
      <Association Name="tblSection_tblSchedule" Member="tblSection" ThisKey="sectionID" OtherKey="sectionID" Type="tblSection" IsForeignKey="true" />
      <Association Name="tblSubject_tblSchedule" Member="tblSubject" ThisKey="subjectID" OtherKey="subjectID" Type="tblSubject" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSection" Member="tblSections">
    <Type Name="tblSection">
      <Column Name="sectionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="sectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="tblSection_tblSchedule" Member="tblSchedules" ThisKey="sectionID" OtherKey="sectionID" Type="tblSchedule" />
      <Association Name="tblSection_tblStudentSection" Member="tblStudentSections" ThisKey="sectionID" OtherKey="sectionID" Type="tblStudentSection" />
    </Type>
  </Table>
  <Table Name="dbo.tblStudent" Member="tblStudents">
    <Type Name="tblStudent">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="gradeLevelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="studentContactNumber" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="studentEmail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="studentAddress" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="studentDateOfBirth" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="studentImage" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="studentGender" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="studentNationality" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="studentStatus" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="paymentPlan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="tblStudent_tblRecord" Member="tblRecords" ThisKey="StudentID" OtherKey="studentID" Type="tblRecord" />
      <Association Name="tblStudent_tblStudentSection" Member="tblStudentSections" ThisKey="StudentID" OtherKey="studentID" Type="tblStudentSection" />
      <Association Name="tblGradeLevel_tblStudent" Member="tblGradeLevel" ThisKey="gradeLevelID" OtherKey="gradeLevelID" Type="tblGradeLevel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblStudentSection" Member="tblStudentSections">
    <Type Name="tblStudentSection">
      <Column Name="studentSectionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="studentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sectionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblSection_tblStudentSection" Member="tblSection" ThisKey="sectionID" OtherKey="sectionID" Type="tblSection" IsForeignKey="true" />
      <Association Name="tblStudent_tblStudentSection" Member="tblStudent" ThisKey="studentID" OtherKey="StudentID" Type="tblStudent" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSubject" Member="tblSubjects">
    <Type Name="tblSubject">
      <Column Name="subjectID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="subjectName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="tblSubject_tblRecord" Member="tblRecords" ThisKey="subjectID" OtherKey="subjectID" Type="tblRecord" />
      <Association Name="tblSubject_tblSchedule" Member="tblSchedules" ThisKey="subjectID" OtherKey="subjectID" Type="tblSchedule" />
    </Type>
  </Table>
</Database>